/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const AddCategoryRequest = IDL.Record({
  'name' : IDL.Text,
  'subcategories' : IDL.Vec(IDL.Text),
});
export const EntityId = IDL.Nat;
export const Timestamp = IDL.Int;
export const QCStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const GRNLineItem = IDL.Record({
  'qty' : IDL.Nat,
  'itemId' : EntityId,
  'total' : IDL.Float64,
  'rate' : IDL.Float64,
  'gstPercent' : IDL.Float64,
  'itemCode' : IDL.Text,
});
export const AddGRNRequest = IDL.Record({
  'challanNo' : IDL.Text,
  'date' : Timestamp,
  'invoiceNo' : IDL.Text,
  'qcStatus' : QCStatus,
  'items' : IDL.Vec(GRNLineItem),
  'supplierId' : EntityId,
});
export const IssueType = IDL.Variant({
  'normal' : IDL.Null,
  'emergencyBreakdown' : IDL.Null,
  'directConsumable' : IDL.Null,
});
export const IssueLineItem = IDL.Record({
  'qty' : IDL.Nat,
  'itemId' : EntityId,
  'itemCode' : IDL.Text,
});
export const AddIssueRequest = IDL.Record({
  'issueType' : IssueType,
  'items' : IDL.Vec(IssueLineItem),
  'department' : IDL.Text,
  'purpose' : IDL.Text,
  'machineName' : IDL.Text,
  'requestedBy' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AddItemRequest = IDL.Record({
  'minimumStock' : IDL.Nat,
  'subcategory' : IDL.Text,
  'code' : IDL.Text,
  'name' : IDL.Text,
  'size' : IDL.Text,
  'unit' : IDL.Text,
  'description' : IDL.Text,
  'rackLocation' : IDL.Text,
  'category' : IDL.Text,
  'gstHsn' : IDL.Text,
  'brand' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
  'preferredSupplier' : IDL.Text,
});
export const AddSupplierRequest = IDL.Record({
  'name' : IDL.Text,
  'contactPerson' : IDL.Text,
  'email' : IDL.Text,
  'gstin' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AuditLog = IDL.Record({
  'id' : EntityId,
  'action' : IDL.Text,
  'oldValue' : IDL.Text,
  'moduleName' : IDL.Text,
  'userId' : IDL.Principal,
  'newValue' : IDL.Text,
  'entityId' : EntityId,
  'timestamp' : Timestamp,
});
export const Role = IDL.Variant({
  'manager' : IDL.Null,
  'admin' : IDL.Null,
  'purchaseUser' : IDL.Null,
  'storeUser' : IDL.Null,
});
export const UserProfilePublic = IDL.Record({
  'id' : IDL.Principal,
  'username' : IDL.Text,
  'lastLoginAt' : IDL.Opt(Timestamp),
  'createdAt' : Timestamp,
  'role' : Role,
  'isActive' : IDL.Bool,
});
export const ItemPublic = IDL.Record({
  'id' : EntityId,
  'minimumStock' : IDL.Nat,
  'subcategory' : IDL.Text,
  'code' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'size' : IDL.Text,
  'unit' : IDL.Text,
  'description' : IDL.Text,
  'rackLocation' : IDL.Text,
  'isActive' : IDL.Bool,
  'updatedAt' : Timestamp,
  'lastPurchaseRate' : IDL.Float64,
  'category' : IDL.Text,
  'gstHsn' : IDL.Text,
  'brand' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
  'currentStock' : IDL.Nat,
  'preferredSupplier' : IDL.Text,
});
export const DashboardStats = IDL.Record({
  'currentStockValue' : IDL.Float64,
  'totalActiveItems' : IDL.Nat,
  'lowStockCount' : IDL.Nat,
  'todayIssueCount' : IDL.Nat,
  'todayInwardCount' : IDL.Nat,
  'nonMovingCount' : IDL.Nat,
});
export const DeptConsumptionStat = IDL.Record({
  'totalValue' : IDL.Float64,
  'totalQty' : IDL.Nat,
  'department' : IDL.Text,
});
export const GRNEntryPublic = IDL.Record({
  'id' : EntityId,
  'challanNo' : IDL.Text,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'createdBy' : IDL.Text,
  'invoiceNo' : IDL.Text,
  'qcStatus' : QCStatus,
  'grnNo' : IDL.Text,
  'items' : IDL.Vec(GRNLineItem),
  'supplierId' : EntityId,
});
export const IssueEntryPublic = IDL.Record({
  'id' : EntityId,
  'status' : IDL.Text,
  'issueType' : IssueType,
  'issueSlipNo' : IDL.Text,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'issuedBy' : IDL.Text,
  'items' : IDL.Vec(IssueLineItem),
  'department' : IDL.Text,
  'purpose' : IDL.Text,
  'machineName' : IDL.Text,
  'requestedBy' : IDL.Text,
});
export const TransactionType = IDL.Variant({
  'inward' : IDL.Null,
  'issue' : IDL.Null,
});
export const StockTransaction = IDL.Record({
  'id' : EntityId,
  'qty' : IDL.Nat,
  'itemId' : EntityId,
  'transactionType' : TransactionType,
  'createdAt' : Timestamp,
  'balanceAfter' : IDL.Nat,
  'refId' : EntityId,
});
export const MonthlyConsumption = IDL.Record({
  'month' : IDL.Text,
  'totalValue' : IDL.Float64,
  'totalQty' : IDL.Nat,
});
export const SupplierPublic = IDL.Record({
  'id' : EntityId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'contactPerson' : IDL.Text,
  'email' : IDL.Text,
  'gstin' : IDL.Text,
  'address' : IDL.Text,
  'ledgerBalance' : IDL.Float64,
  'phone' : IDL.Text,
});
export const ItemUsageStat = IDL.Record({
  'itemId' : EntityId,
  'totalQty' : IDL.Nat,
  'itemCode' : IDL.Text,
  'itemName' : IDL.Text,
});
export const CategoryPublic = IDL.Record({
  'id' : EntityId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'subcategories' : IDL.Vec(IDL.Text),
});
export const UpdateItemRequest = IDL.Record({
  'minimumStock' : IDL.Nat,
  'subcategory' : IDL.Text,
  'name' : IDL.Text,
  'size' : IDL.Text,
  'unit' : IDL.Text,
  'description' : IDL.Text,
  'rackLocation' : IDL.Text,
  'category' : IDL.Text,
  'gstHsn' : IDL.Text,
  'brand' : IDL.Text,
  'photo' : IDL.Opt(ExternalBlob),
  'preferredSupplier' : IDL.Text,
});
export const UpdateSupplierRequest = IDL.Record({
  'name' : IDL.Text,
  'contactPerson' : IDL.Text,
  'email' : IDL.Text,
  'gstin' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addCategory' : IDL.Func([AddCategoryRequest], [EntityId], []),
  'addGRN' : IDL.Func([AddGRNRequest], [EntityId], []),
  'addIssue' : IDL.Func([AddIssueRequest], [EntityId], []),
  'addItem' : IDL.Func([AddItemRequest], [EntityId], []),
  'addSupplier' : IDL.Func([AddSupplierRequest], [EntityId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deactivateItem' : IDL.Func([EntityId], [IDL.Bool], []),
  'deactivateUser' : IDL.Func([IDL.Principal], [IDL.Bool], []),
  'deleteCategory' : IDL.Func([EntityId], [IDL.Bool], []),
  'deleteSupplier' : IDL.Func([EntityId], [IDL.Bool], []),
  'getAuditLogs' : IDL.Func([], [IDL.Vec(AuditLog)], ['query']),
  'getCallerUserProfile' : IDL.Func(
      [],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentStock' : IDL.Func([], [IDL.Vec(ItemPublic)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getDeadStockReport' : IDL.Func([IDL.Nat], [IDL.Vec(ItemPublic)], ['query']),
  'getDeptConsumption' : IDL.Func(
      [],
      [IDL.Vec(DeptConsumptionStat)],
      ['query'],
    ),
  'getDeptConsumptionReport' : IDL.Func(
      [Timestamp, Timestamp],
      [IDL.Vec(DeptConsumptionStat)],
      ['query'],
    ),
  'getGRN' : IDL.Func([EntityId], [IDL.Opt(GRNEntryPublic)], ['query']),
  'getIssue' : IDL.Func([EntityId], [IDL.Opt(IssueEntryPublic)], ['query']),
  'getItem' : IDL.Func([EntityId], [IDL.Opt(ItemPublic)], ['query']),
  'getItemLedger' : IDL.Func(
      [EntityId],
      [IDL.Vec(StockTransaction)],
      ['query'],
    ),
  'getItemLedgerReport' : IDL.Func(
      [EntityId],
      [IDL.Vec(StockTransaction)],
      ['query'],
    ),
  'getLowStockItems' : IDL.Func([], [IDL.Vec(ItemPublic)], ['query']),
  'getLowStockReport' : IDL.Func([], [IDL.Vec(ItemPublic)], ['query']),
  'getMonthlyConsumption' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(MonthlyConsumption)],
      ['query'],
    ),
  'getMonthlyPurchaseReport' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(MonthlyConsumption)],
      ['query'],
    ),
  'getSupplier' : IDL.Func([EntityId], [IDL.Opt(SupplierPublic)], ['query']),
  'getTopUsedItems' : IDL.Func([IDL.Nat], [IDL.Vec(ItemUsageStat)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfilePublic)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listCategories' : IDL.Func([], [IDL.Vec(CategoryPublic)], ['query']),
  'listGRNs' : IDL.Func([], [IDL.Vec(GRNEntryPublic)], ['query']),
  'listIssues' : IDL.Func([], [IDL.Vec(IssueEntryPublic)], ['query']),
  'listItems' : IDL.Func([], [IDL.Vec(ItemPublic)], ['query']),
  'listSuppliers' : IDL.Func([], [IDL.Vec(SupplierPublic)], ['query']),
  'listUsers' : IDL.Func([], [IDL.Vec(UserProfilePublic)], ['query']),
  'saveCallerUserProfile' : IDL.Func([IDL.Text], [], []),
  'searchItems' : IDL.Func([IDL.Text], [IDL.Vec(ItemPublic)], ['query']),
  'updateCategory' : IDL.Func(
      [EntityId, IDL.Text, IDL.Vec(IDL.Text)],
      [IDL.Bool],
      [],
    ),
  'updateGRNQCStatus' : IDL.Func([EntityId, QCStatus], [IDL.Bool], []),
  'updateItem' : IDL.Func([EntityId, UpdateItemRequest], [IDL.Bool], []),
  'updateSupplier' : IDL.Func(
      [EntityId, UpdateSupplierRequest],
      [IDL.Bool],
      [],
    ),
  'uploadItemPhoto' : IDL.Func([EntityId, ExternalBlob], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const AddCategoryRequest = IDL.Record({
    'name' : IDL.Text,
    'subcategories' : IDL.Vec(IDL.Text),
  });
  const EntityId = IDL.Nat;
  const Timestamp = IDL.Int;
  const QCStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const GRNLineItem = IDL.Record({
    'qty' : IDL.Nat,
    'itemId' : EntityId,
    'total' : IDL.Float64,
    'rate' : IDL.Float64,
    'gstPercent' : IDL.Float64,
    'itemCode' : IDL.Text,
  });
  const AddGRNRequest = IDL.Record({
    'challanNo' : IDL.Text,
    'date' : Timestamp,
    'invoiceNo' : IDL.Text,
    'qcStatus' : QCStatus,
    'items' : IDL.Vec(GRNLineItem),
    'supplierId' : EntityId,
  });
  const IssueType = IDL.Variant({
    'normal' : IDL.Null,
    'emergencyBreakdown' : IDL.Null,
    'directConsumable' : IDL.Null,
  });
  const IssueLineItem = IDL.Record({
    'qty' : IDL.Nat,
    'itemId' : EntityId,
    'itemCode' : IDL.Text,
  });
  const AddIssueRequest = IDL.Record({
    'issueType' : IssueType,
    'items' : IDL.Vec(IssueLineItem),
    'department' : IDL.Text,
    'purpose' : IDL.Text,
    'machineName' : IDL.Text,
    'requestedBy' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AddItemRequest = IDL.Record({
    'minimumStock' : IDL.Nat,
    'subcategory' : IDL.Text,
    'code' : IDL.Text,
    'name' : IDL.Text,
    'size' : IDL.Text,
    'unit' : IDL.Text,
    'description' : IDL.Text,
    'rackLocation' : IDL.Text,
    'category' : IDL.Text,
    'gstHsn' : IDL.Text,
    'brand' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
    'preferredSupplier' : IDL.Text,
  });
  const AddSupplierRequest = IDL.Record({
    'name' : IDL.Text,
    'contactPerson' : IDL.Text,
    'email' : IDL.Text,
    'gstin' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AuditLog = IDL.Record({
    'id' : EntityId,
    'action' : IDL.Text,
    'oldValue' : IDL.Text,
    'moduleName' : IDL.Text,
    'userId' : IDL.Principal,
    'newValue' : IDL.Text,
    'entityId' : EntityId,
    'timestamp' : Timestamp,
  });
  const Role = IDL.Variant({
    'manager' : IDL.Null,
    'admin' : IDL.Null,
    'purchaseUser' : IDL.Null,
    'storeUser' : IDL.Null,
  });
  const UserProfilePublic = IDL.Record({
    'id' : IDL.Principal,
    'username' : IDL.Text,
    'lastLoginAt' : IDL.Opt(Timestamp),
    'createdAt' : Timestamp,
    'role' : Role,
    'isActive' : IDL.Bool,
  });
  const ItemPublic = IDL.Record({
    'id' : EntityId,
    'minimumStock' : IDL.Nat,
    'subcategory' : IDL.Text,
    'code' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'size' : IDL.Text,
    'unit' : IDL.Text,
    'description' : IDL.Text,
    'rackLocation' : IDL.Text,
    'isActive' : IDL.Bool,
    'updatedAt' : Timestamp,
    'lastPurchaseRate' : IDL.Float64,
    'category' : IDL.Text,
    'gstHsn' : IDL.Text,
    'brand' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
    'currentStock' : IDL.Nat,
    'preferredSupplier' : IDL.Text,
  });
  const DashboardStats = IDL.Record({
    'currentStockValue' : IDL.Float64,
    'totalActiveItems' : IDL.Nat,
    'lowStockCount' : IDL.Nat,
    'todayIssueCount' : IDL.Nat,
    'todayInwardCount' : IDL.Nat,
    'nonMovingCount' : IDL.Nat,
  });
  const DeptConsumptionStat = IDL.Record({
    'totalValue' : IDL.Float64,
    'totalQty' : IDL.Nat,
    'department' : IDL.Text,
  });
  const GRNEntryPublic = IDL.Record({
    'id' : EntityId,
    'challanNo' : IDL.Text,
    'date' : Timestamp,
    'createdAt' : Timestamp,
    'createdBy' : IDL.Text,
    'invoiceNo' : IDL.Text,
    'qcStatus' : QCStatus,
    'grnNo' : IDL.Text,
    'items' : IDL.Vec(GRNLineItem),
    'supplierId' : EntityId,
  });
  const IssueEntryPublic = IDL.Record({
    'id' : EntityId,
    'status' : IDL.Text,
    'issueType' : IssueType,
    'issueSlipNo' : IDL.Text,
    'date' : Timestamp,
    'createdAt' : Timestamp,
    'issuedBy' : IDL.Text,
    'items' : IDL.Vec(IssueLineItem),
    'department' : IDL.Text,
    'purpose' : IDL.Text,
    'machineName' : IDL.Text,
    'requestedBy' : IDL.Text,
  });
  const TransactionType = IDL.Variant({
    'inward' : IDL.Null,
    'issue' : IDL.Null,
  });
  const StockTransaction = IDL.Record({
    'id' : EntityId,
    'qty' : IDL.Nat,
    'itemId' : EntityId,
    'transactionType' : TransactionType,
    'createdAt' : Timestamp,
    'balanceAfter' : IDL.Nat,
    'refId' : EntityId,
  });
  const MonthlyConsumption = IDL.Record({
    'month' : IDL.Text,
    'totalValue' : IDL.Float64,
    'totalQty' : IDL.Nat,
  });
  const SupplierPublic = IDL.Record({
    'id' : EntityId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'contactPerson' : IDL.Text,
    'email' : IDL.Text,
    'gstin' : IDL.Text,
    'address' : IDL.Text,
    'ledgerBalance' : IDL.Float64,
    'phone' : IDL.Text,
  });
  const ItemUsageStat = IDL.Record({
    'itemId' : EntityId,
    'totalQty' : IDL.Nat,
    'itemCode' : IDL.Text,
    'itemName' : IDL.Text,
  });
  const CategoryPublic = IDL.Record({
    'id' : EntityId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'subcategories' : IDL.Vec(IDL.Text),
  });
  const UpdateItemRequest = IDL.Record({
    'minimumStock' : IDL.Nat,
    'subcategory' : IDL.Text,
    'name' : IDL.Text,
    'size' : IDL.Text,
    'unit' : IDL.Text,
    'description' : IDL.Text,
    'rackLocation' : IDL.Text,
    'category' : IDL.Text,
    'gstHsn' : IDL.Text,
    'brand' : IDL.Text,
    'photo' : IDL.Opt(ExternalBlob),
    'preferredSupplier' : IDL.Text,
  });
  const UpdateSupplierRequest = IDL.Record({
    'name' : IDL.Text,
    'contactPerson' : IDL.Text,
    'email' : IDL.Text,
    'gstin' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addCategory' : IDL.Func([AddCategoryRequest], [EntityId], []),
    'addGRN' : IDL.Func([AddGRNRequest], [EntityId], []),
    'addIssue' : IDL.Func([AddIssueRequest], [EntityId], []),
    'addItem' : IDL.Func([AddItemRequest], [EntityId], []),
    'addSupplier' : IDL.Func([AddSupplierRequest], [EntityId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deactivateItem' : IDL.Func([EntityId], [IDL.Bool], []),
    'deactivateUser' : IDL.Func([IDL.Principal], [IDL.Bool], []),
    'deleteCategory' : IDL.Func([EntityId], [IDL.Bool], []),
    'deleteSupplier' : IDL.Func([EntityId], [IDL.Bool], []),
    'getAuditLogs' : IDL.Func([], [IDL.Vec(AuditLog)], ['query']),
    'getCallerUserProfile' : IDL.Func(
        [],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentStock' : IDL.Func([], [IDL.Vec(ItemPublic)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getDeadStockReport' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ItemPublic)],
        ['query'],
      ),
    'getDeptConsumption' : IDL.Func(
        [],
        [IDL.Vec(DeptConsumptionStat)],
        ['query'],
      ),
    'getDeptConsumptionReport' : IDL.Func(
        [Timestamp, Timestamp],
        [IDL.Vec(DeptConsumptionStat)],
        ['query'],
      ),
    'getGRN' : IDL.Func([EntityId], [IDL.Opt(GRNEntryPublic)], ['query']),
    'getIssue' : IDL.Func([EntityId], [IDL.Opt(IssueEntryPublic)], ['query']),
    'getItem' : IDL.Func([EntityId], [IDL.Opt(ItemPublic)], ['query']),
    'getItemLedger' : IDL.Func(
        [EntityId],
        [IDL.Vec(StockTransaction)],
        ['query'],
      ),
    'getItemLedgerReport' : IDL.Func(
        [EntityId],
        [IDL.Vec(StockTransaction)],
        ['query'],
      ),
    'getLowStockItems' : IDL.Func([], [IDL.Vec(ItemPublic)], ['query']),
    'getLowStockReport' : IDL.Func([], [IDL.Vec(ItemPublic)], ['query']),
    'getMonthlyConsumption' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MonthlyConsumption)],
        ['query'],
      ),
    'getMonthlyPurchaseReport' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(MonthlyConsumption)],
        ['query'],
      ),
    'getSupplier' : IDL.Func([EntityId], [IDL.Opt(SupplierPublic)], ['query']),
    'getTopUsedItems' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ItemUsageStat)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfilePublic)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listCategories' : IDL.Func([], [IDL.Vec(CategoryPublic)], ['query']),
    'listGRNs' : IDL.Func([], [IDL.Vec(GRNEntryPublic)], ['query']),
    'listIssues' : IDL.Func([], [IDL.Vec(IssueEntryPublic)], ['query']),
    'listItems' : IDL.Func([], [IDL.Vec(ItemPublic)], ['query']),
    'listSuppliers' : IDL.Func([], [IDL.Vec(SupplierPublic)], ['query']),
    'listUsers' : IDL.Func([], [IDL.Vec(UserProfilePublic)], ['query']),
    'saveCallerUserProfile' : IDL.Func([IDL.Text], [], []),
    'searchItems' : IDL.Func([IDL.Text], [IDL.Vec(ItemPublic)], ['query']),
    'updateCategory' : IDL.Func(
        [EntityId, IDL.Text, IDL.Vec(IDL.Text)],
        [IDL.Bool],
        [],
      ),
    'updateGRNQCStatus' : IDL.Func([EntityId, QCStatus], [IDL.Bool], []),
    'updateItem' : IDL.Func([EntityId, UpdateItemRequest], [IDL.Bool], []),
    'updateSupplier' : IDL.Func(
        [EntityId, UpdateSupplierRequest],
        [IDL.Bool],
        [],
      ),
    'uploadItemPhoto' : IDL.Func([EntityId, ExternalBlob], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };