/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AddCategoryRequest {
  'name' : string,
  'subcategories' : Array<string>,
}
export interface AddGRNRequest {
  'challanNo' : string,
  'date' : Timestamp,
  'invoiceNo' : string,
  'qcStatus' : QCStatus,
  'items' : Array<GRNLineItem>,
  'supplierId' : EntityId,
}
export interface AddIssueRequest {
  'issueType' : IssueType,
  'items' : Array<IssueLineItem>,
  'department' : string,
  'purpose' : string,
  'machineName' : string,
  'requestedBy' : string,
}
export interface AddItemRequest {
  'minimumStock' : bigint,
  'subcategory' : string,
  'code' : string,
  'name' : string,
  'size' : string,
  'unit' : string,
  'description' : string,
  'rackLocation' : string,
  'category' : string,
  'gstHsn' : string,
  'brand' : string,
  'photo' : [] | [ExternalBlob],
  'preferredSupplier' : string,
}
export interface AddSupplierRequest {
  'name' : string,
  'contactPerson' : string,
  'email' : string,
  'gstin' : string,
  'address' : string,
  'phone' : string,
}
export interface AuditLog {
  'id' : EntityId,
  'action' : string,
  'oldValue' : string,
  'moduleName' : string,
  'userId' : Principal,
  'newValue' : string,
  'entityId' : EntityId,
  'timestamp' : Timestamp,
}
export interface CategoryPublic {
  'id' : EntityId,
  'name' : string,
  'createdAt' : Timestamp,
  'subcategories' : Array<string>,
}
export interface DashboardStats {
  'currentStockValue' : number,
  'totalActiveItems' : bigint,
  'lowStockCount' : bigint,
  'todayIssueCount' : bigint,
  'todayInwardCount' : bigint,
  'nonMovingCount' : bigint,
}
export interface DeptConsumptionStat {
  'totalValue' : number,
  'totalQty' : bigint,
  'department' : string,
}
export type EntityId = bigint;
export type ExternalBlob = Uint8Array;
export interface GRNEntryPublic {
  'id' : EntityId,
  'challanNo' : string,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'createdBy' : string,
  'invoiceNo' : string,
  'qcStatus' : QCStatus,
  'grnNo' : string,
  'items' : Array<GRNLineItem>,
  'supplierId' : EntityId,
}
export interface GRNLineItem {
  'qty' : bigint,
  'itemId' : EntityId,
  'total' : number,
  'rate' : number,
  'gstPercent' : number,
  'itemCode' : string,
}
export interface IssueEntryPublic {
  'id' : EntityId,
  'status' : string,
  'issueType' : IssueType,
  'issueSlipNo' : string,
  'date' : Timestamp,
  'createdAt' : Timestamp,
  'issuedBy' : string,
  'items' : Array<IssueLineItem>,
  'department' : string,
  'purpose' : string,
  'machineName' : string,
  'requestedBy' : string,
}
export interface IssueLineItem {
  'qty' : bigint,
  'itemId' : EntityId,
  'itemCode' : string,
}
export type IssueType = { 'normal' : null } |
  { 'emergencyBreakdown' : null } |
  { 'directConsumable' : null };
export interface ItemPublic {
  'id' : EntityId,
  'minimumStock' : bigint,
  'subcategory' : string,
  'code' : string,
  'name' : string,
  'createdAt' : Timestamp,
  'size' : string,
  'unit' : string,
  'description' : string,
  'rackLocation' : string,
  'isActive' : boolean,
  'updatedAt' : Timestamp,
  'lastPurchaseRate' : number,
  'category' : string,
  'gstHsn' : string,
  'brand' : string,
  'photo' : [] | [ExternalBlob],
  'currentStock' : bigint,
  'preferredSupplier' : string,
}
export interface ItemUsageStat {
  'itemId' : EntityId,
  'totalQty' : bigint,
  'itemCode' : string,
  'itemName' : string,
}
export interface MonthlyConsumption {
  'month' : string,
  'totalValue' : number,
  'totalQty' : bigint,
}
export type QCStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type Role = { 'manager' : null } |
  { 'admin' : null } |
  { 'purchaseUser' : null } |
  { 'storeUser' : null };
export interface StockTransaction {
  'id' : EntityId,
  'qty' : bigint,
  'itemId' : EntityId,
  'transactionType' : TransactionType,
  'createdAt' : Timestamp,
  'balanceAfter' : bigint,
  'refId' : EntityId,
}
export interface SupplierPublic {
  'id' : EntityId,
  'name' : string,
  'createdAt' : Timestamp,
  'contactPerson' : string,
  'email' : string,
  'gstin' : string,
  'address' : string,
  'ledgerBalance' : number,
  'phone' : string,
}
export type Timestamp = bigint;
export type TransactionType = { 'inward' : null } |
  { 'issue' : null };
export interface UpdateItemRequest {
  'minimumStock' : bigint,
  'subcategory' : string,
  'name' : string,
  'size' : string,
  'unit' : string,
  'description' : string,
  'rackLocation' : string,
  'category' : string,
  'gstHsn' : string,
  'brand' : string,
  'photo' : [] | [ExternalBlob],
  'preferredSupplier' : string,
}
export interface UpdateSupplierRequest {
  'name' : string,
  'contactPerson' : string,
  'email' : string,
  'gstin' : string,
  'address' : string,
  'phone' : string,
}
export interface UserProfilePublic {
  'id' : Principal,
  'username' : string,
  'lastLoginAt' : [] | [Timestamp],
  'createdAt' : Timestamp,
  'role' : Role,
  'isActive' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addCategory' : ActorMethod<[AddCategoryRequest], EntityId>,
  'addGRN' : ActorMethod<[AddGRNRequest], EntityId>,
  'addIssue' : ActorMethod<[AddIssueRequest], EntityId>,
  'addItem' : ActorMethod<[AddItemRequest], EntityId>,
  'addSupplier' : ActorMethod<[AddSupplierRequest], EntityId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deactivateItem' : ActorMethod<[EntityId], boolean>,
  'deactivateUser' : ActorMethod<[Principal], boolean>,
  'deleteCategory' : ActorMethod<[EntityId], boolean>,
  'deleteSupplier' : ActorMethod<[EntityId], boolean>,
  'getAuditLogs' : ActorMethod<[], Array<AuditLog>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentStock' : ActorMethod<[], Array<ItemPublic>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getDeadStockReport' : ActorMethod<[bigint], Array<ItemPublic>>,
  'getDeptConsumption' : ActorMethod<[], Array<DeptConsumptionStat>>,
  'getDeptConsumptionReport' : ActorMethod<
    [Timestamp, Timestamp],
    Array<DeptConsumptionStat>
  >,
  'getGRN' : ActorMethod<[EntityId], [] | [GRNEntryPublic]>,
  'getIssue' : ActorMethod<[EntityId], [] | [IssueEntryPublic]>,
  'getItem' : ActorMethod<[EntityId], [] | [ItemPublic]>,
  'getItemLedger' : ActorMethod<[EntityId], Array<StockTransaction>>,
  'getItemLedgerReport' : ActorMethod<[EntityId], Array<StockTransaction>>,
  'getLowStockItems' : ActorMethod<[], Array<ItemPublic>>,
  'getLowStockReport' : ActorMethod<[], Array<ItemPublic>>,
  'getMonthlyConsumption' : ActorMethod<[bigint], Array<MonthlyConsumption>>,
  'getMonthlyPurchaseReport' : ActorMethod<[bigint], Array<MonthlyConsumption>>,
  'getSupplier' : ActorMethod<[EntityId], [] | [SupplierPublic]>,
  'getTopUsedItems' : ActorMethod<[bigint], Array<ItemUsageStat>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfilePublic]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listCategories' : ActorMethod<[], Array<CategoryPublic>>,
  'listGRNs' : ActorMethod<[], Array<GRNEntryPublic>>,
  'listIssues' : ActorMethod<[], Array<IssueEntryPublic>>,
  'listItems' : ActorMethod<[], Array<ItemPublic>>,
  'listSuppliers' : ActorMethod<[], Array<SupplierPublic>>,
  'listUsers' : ActorMethod<[], Array<UserProfilePublic>>,
  'saveCallerUserProfile' : ActorMethod<[string], undefined>,
  'searchItems' : ActorMethod<[string], Array<ItemPublic>>,
  'updateCategory' : ActorMethod<[EntityId, string, Array<string>], boolean>,
  'updateGRNQCStatus' : ActorMethod<[EntityId, QCStatus], boolean>,
  'updateItem' : ActorMethod<[EntityId, UpdateItemRequest], boolean>,
  'updateSupplier' : ActorMethod<[EntityId, UpdateSupplierRequest], boolean>,
  'uploadItemPhoto' : ActorMethod<[EntityId, ExternalBlob], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];