/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MonthlyConsumption {
    month: string;
    totalValue: number;
    totalQty: bigint;
}
export interface ItemUsageStat {
    itemId: EntityId;
    totalQty: bigint;
    itemCode: string;
    itemName: string;
}
export type Timestamp = bigint;
export interface IssueLineItem {
    qty: bigint;
    itemId: EntityId;
    itemCode: string;
}
export interface AuditLog {
    id: EntityId;
    action: string;
    oldValue: string;
    moduleName: string;
    userId: Principal;
    newValue: string;
    entityId: EntityId;
    timestamp: Timestamp;
}
export interface CategoryPublic {
    id: EntityId;
    name: string;
    createdAt: Timestamp;
    subcategories: Array<string>;
}
export type EntityId = bigint;
export interface AddItemRequest {
    minimumStock: bigint;
    subcategory: string;
    code: string;
    name: string;
    size: string;
    unit: string;
    description: string;
    rackLocation: string;
    category: string;
    gstHsn: string;
    brand: string;
    photo?: ExternalBlob;
    preferredSupplier: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface SupplierPublic {
    id: EntityId;
    name: string;
    createdAt: Timestamp;
    contactPerson: string;
    email: string;
    gstin: string;
    address: string;
    ledgerBalance: number;
    phone: string;
}
export interface ItemPublic {
    id: EntityId;
    minimumStock: bigint;
    subcategory: string;
    code: string;
    name: string;
    createdAt: Timestamp;
    size: string;
    unit: string;
    description: string;
    rackLocation: string;
    isActive: boolean;
    updatedAt: Timestamp;
    lastPurchaseRate: number;
    category: string;
    gstHsn: string;
    brand: string;
    photo?: ExternalBlob;
    currentStock: bigint;
    preferredSupplier: string;
}
export interface GRNLineItem {
    qty: bigint;
    itemId: EntityId;
    total: number;
    rate: number;
    gstPercent: number;
    itemCode: string;
}
export interface DeptConsumptionStat {
    totalValue: number;
    totalQty: bigint;
    department: string;
}
export interface UpdateSupplierRequest {
    name: string;
    contactPerson: string;
    email: string;
    gstin: string;
    address: string;
    phone: string;
}
export interface IssueEntryPublic {
    id: EntityId;
    status: string;
    issueType: IssueType;
    issueSlipNo: string;
    date: Timestamp;
    createdAt: Timestamp;
    issuedBy: string;
    items: Array<IssueLineItem>;
    department: string;
    purpose: string;
    machineName: string;
    requestedBy: string;
}
export interface UpdateItemRequest {
    minimumStock: bigint;
    subcategory: string;
    name: string;
    size: string;
    unit: string;
    description: string;
    rackLocation: string;
    category: string;
    gstHsn: string;
    brand: string;
    photo?: ExternalBlob;
    preferredSupplier: string;
}
export interface AddSupplierRequest {
    name: string;
    contactPerson: string;
    email: string;
    gstin: string;
    address: string;
    phone: string;
}
export interface AddIssueRequest {
    issueType: IssueType;
    items: Array<IssueLineItem>;
    department: string;
    purpose: string;
    machineName: string;
    requestedBy: string;
}
export interface AddCategoryRequest {
    name: string;
    subcategories: Array<string>;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface StockTransaction {
    id: EntityId;
    qty: bigint;
    itemId: EntityId;
    transactionType: TransactionType;
    createdAt: Timestamp;
    balanceAfter: bigint;
    refId: EntityId;
}
export interface DashboardStats {
    currentStockValue: number;
    totalActiveItems: bigint;
    lowStockCount: bigint;
    todayIssueCount: bigint;
    todayInwardCount: bigint;
    nonMovingCount: bigint;
}
export interface UserProfilePublic {
    id: Principal;
    username: string;
    lastLoginAt?: Timestamp;
    createdAt: Timestamp;
    role: Role;
    isActive: boolean;
}
export interface GRNEntryPublic {
    id: EntityId;
    challanNo: string;
    date: Timestamp;
    createdAt: Timestamp;
    createdBy: string;
    invoiceNo: string;
    qcStatus: QCStatus;
    grnNo: string;
    items: Array<GRNLineItem>;
    supplierId: EntityId;
}
export interface AddGRNRequest {
    challanNo: string;
    date: Timestamp;
    invoiceNo: string;
    qcStatus: QCStatus;
    items: Array<GRNLineItem>;
    supplierId: EntityId;
}
export enum IssueType {
    normal = "normal",
    emergencyBreakdown = "emergencyBreakdown",
    directConsumable = "directConsumable"
}
export enum QCStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum Role {
    manager = "manager",
    admin = "admin",
    purchaseUser = "purchaseUser",
    storeUser = "storeUser"
}
export enum TransactionType {
    inward = "inward",
    issue = "issue"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    addCategory(req: AddCategoryRequest): Promise<EntityId>;
    addGRN(req: AddGRNRequest): Promise<EntityId>;
    addIssue(req: AddIssueRequest): Promise<EntityId>;
    addItem(req: AddItemRequest): Promise<EntityId>;
    addSupplier(req: AddSupplierRequest): Promise<EntityId>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deactivateItem(id: EntityId): Promise<boolean>;
    deactivateUser(userId: Principal): Promise<boolean>;
    deleteCategory(id: EntityId): Promise<boolean>;
    deleteSupplier(id: EntityId): Promise<boolean>;
    getAuditLogs(): Promise<Array<AuditLog>>;
    getCallerUserProfile(): Promise<UserProfilePublic | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentStock(): Promise<Array<ItemPublic>>;
    getDashboardStats(): Promise<DashboardStats>;
    getDeadStockReport(thresholdDays: bigint): Promise<Array<ItemPublic>>;
    getDeptConsumption(): Promise<Array<DeptConsumptionStat>>;
    getDeptConsumptionReport(fromTs: Timestamp, toTs: Timestamp): Promise<Array<DeptConsumptionStat>>;
    getGRN(id: EntityId): Promise<GRNEntryPublic | null>;
    getIssue(id: EntityId): Promise<IssueEntryPublic | null>;
    getItem(id: EntityId): Promise<ItemPublic | null>;
    getItemLedger(itemId: EntityId): Promise<Array<StockTransaction>>;
    getItemLedgerReport(itemId: EntityId): Promise<Array<StockTransaction>>;
    getLowStockItems(): Promise<Array<ItemPublic>>;
    getLowStockReport(): Promise<Array<ItemPublic>>;
    getMonthlyConsumption(months: bigint): Promise<Array<MonthlyConsumption>>;
    getMonthlyPurchaseReport(months: bigint): Promise<Array<MonthlyConsumption>>;
    getSupplier(id: EntityId): Promise<SupplierPublic | null>;
    getTopUsedItems(limit: bigint): Promise<Array<ItemUsageStat>>;
    getUserProfile(userId: Principal): Promise<UserProfilePublic | null>;
    isCallerAdmin(): Promise<boolean>;
    listCategories(): Promise<Array<CategoryPublic>>;
    listGRNs(): Promise<Array<GRNEntryPublic>>;
    listIssues(): Promise<Array<IssueEntryPublic>>;
    listItems(): Promise<Array<ItemPublic>>;
    listSuppliers(): Promise<Array<SupplierPublic>>;
    listUsers(): Promise<Array<UserProfilePublic>>;
    saveCallerUserProfile(username: string): Promise<void>;
    searchItems(searchTerm: string): Promise<Array<ItemPublic>>;
    updateCategory(id: EntityId, name: string, subcategories: Array<string>): Promise<boolean>;
    updateGRNQCStatus(id: EntityId, status: QCStatus): Promise<boolean>;
    updateItem(id: EntityId, req: UpdateItemRequest): Promise<boolean>;
    updateSupplier(id: EntityId, req: UpdateSupplierRequest): Promise<boolean>;
    uploadItemPhoto(id: EntityId, photo: ExternalBlob): Promise<boolean>;
}
import type { AddGRNRequest as _AddGRNRequest, AddIssueRequest as _AddIssueRequest, AddItemRequest as _AddItemRequest, EntityId as _EntityId, ExternalBlob as _ExternalBlob, GRNEntryPublic as _GRNEntryPublic, GRNLineItem as _GRNLineItem, IssueEntryPublic as _IssueEntryPublic, IssueLineItem as _IssueLineItem, IssueType as _IssueType, ItemPublic as _ItemPublic, QCStatus as _QCStatus, Role as _Role, StockTransaction as _StockTransaction, SupplierPublic as _SupplierPublic, Timestamp as _Timestamp, TransactionType as _TransactionType, UpdateItemRequest as _UpdateItemRequest, UserProfilePublic as _UserProfilePublic, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addCategory(arg0: AddCategoryRequest): Promise<EntityId> {
        if (this.processError) {
            try {
                const result = await this.actor.addCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCategory(arg0);
            return result;
        }
    }
    async addGRN(arg0: AddGRNRequest): Promise<EntityId> {
        if (this.processError) {
            try {
                const result = await this.actor.addGRN(to_candid_AddGRNRequest_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGRN(to_candid_AddGRNRequest_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addIssue(arg0: AddIssueRequest): Promise<EntityId> {
        if (this.processError) {
            try {
                const result = await this.actor.addIssue(to_candid_AddIssueRequest_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIssue(to_candid_AddIssueRequest_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addItem(arg0: AddItemRequest): Promise<EntityId> {
        if (this.processError) {
            try {
                const result = await this.actor.addItem(await to_candid_AddItemRequest_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addItem(await to_candid_AddItemRequest_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addSupplier(arg0: AddSupplierRequest): Promise<EntityId> {
        if (this.processError) {
            try {
                const result = await this.actor.addSupplier(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSupplier(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deactivateItem(arg0: EntityId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateItem(arg0);
            return result;
        }
    }
    async deactivateUser(arg0: Principal): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateUser(arg0);
            return result;
        }
    }
    async deleteCategory(arg0: EntityId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCategory(arg0);
            return result;
        }
    }
    async deleteSupplier(arg0: EntityId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteSupplier(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteSupplier(arg0);
            return result;
        }
    }
    async getAuditLogs(): Promise<Array<AuditLog>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAuditLogs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAuditLogs();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentStock(): Promise<Array<ItemPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentStock();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentStock();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return result;
        }
    }
    async getDeadStockReport(arg0: bigint): Promise<Array<ItemPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeadStockReport(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeadStockReport(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDeptConsumption(): Promise<Array<DeptConsumptionStat>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeptConsumption();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeptConsumption();
            return result;
        }
    }
    async getDeptConsumptionReport(arg0: Timestamp, arg1: Timestamp): Promise<Array<DeptConsumptionStat>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDeptConsumptionReport(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDeptConsumptionReport(arg0, arg1);
            return result;
        }
    }
    async getGRN(arg0: EntityId): Promise<GRNEntryPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGRN(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGRN(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getIssue(arg0: EntityId): Promise<IssueEntryPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getIssue(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getIssue(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getItem(arg0: EntityId): Promise<ItemPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getItem(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItem(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getItemLedger(arg0: EntityId): Promise<Array<StockTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getItemLedger(arg0);
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItemLedger(arg0);
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getItemLedgerReport(arg0: EntityId): Promise<Array<StockTransaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getItemLedgerReport(arg0);
                return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getItemLedgerReport(arg0);
            return from_candid_vec_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLowStockItems(): Promise<Array<ItemPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLowStockItems();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLowStockItems();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLowStockReport(): Promise<Array<ItemPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLowStockReport();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLowStockReport();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMonthlyConsumption(arg0: bigint): Promise<Array<MonthlyConsumption>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyConsumption(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyConsumption(arg0);
            return result;
        }
    }
    async getMonthlyPurchaseReport(arg0: bigint): Promise<Array<MonthlyConsumption>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMonthlyPurchaseReport(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMonthlyPurchaseReport(arg0);
            return result;
        }
    }
    async getSupplier(arg0: EntityId): Promise<SupplierPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSupplier(arg0);
                return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSupplier(arg0);
            return from_candid_opt_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTopUsedItems(arg0: bigint): Promise<Array<ItemUsageStat>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTopUsedItems(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTopUsedItems(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listCategories(): Promise<Array<CategoryPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCategories();
            return result;
        }
    }
    async listGRNs(): Promise<Array<GRNEntryPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listGRNs();
                return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listGRNs();
            return from_candid_vec_n51(this._uploadFile, this._downloadFile, result);
        }
    }
    async listIssues(): Promise<Array<IssueEntryPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listIssues();
                return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listIssues();
            return from_candid_vec_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async listItems(): Promise<Array<ItemPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listItems();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listItems();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async listSuppliers(): Promise<Array<SupplierPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSuppliers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSuppliers();
            return result;
        }
    }
    async listUsers(): Promise<Array<UserProfilePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listUsers();
                return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listUsers();
            return from_candid_vec_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchItems(arg0: string): Promise<Array<ItemPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchItems(arg0);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchItems(arg0);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCategory(arg0: EntityId, arg1: string, arg2: Array<string>): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCategory(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCategory(arg0, arg1, arg2);
            return result;
        }
    }
    async updateGRNQCStatus(arg0: EntityId, arg1: QCStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGRNQCStatus(arg0, to_candid_QCStatus_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGRNQCStatus(arg0, to_candid_QCStatus_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateItem(arg0: EntityId, arg1: UpdateItemRequest): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateItem(arg0, await to_candid_UpdateItemRequest_n54(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateItem(arg0, await to_candid_UpdateItemRequest_n54(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSupplier(arg0: EntityId, arg1: UpdateSupplierRequest): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSupplier(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSupplier(arg0, arg1);
            return result;
        }
    }
    async uploadItemPhoto(arg0: EntityId, arg1: ExternalBlob): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadItemPhoto(arg0, await to_candid_ExternalBlob_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadItemPhoto(arg0, await to_candid_ExternalBlob_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
async function from_candid_ExternalBlob_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_GRNEntryPublic_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GRNEntryPublic): GRNEntryPublic {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_IssueEntryPublic_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IssueEntryPublic): IssueEntryPublic {
    return from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_IssueType_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _IssueType): IssueType {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
async function from_candid_ItemPublic_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ItemPublic): Promise<ItemPublic> {
    return await from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_QCStatus_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _QCStatus): QCStatus {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_StockTransaction_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StockTransaction): StockTransaction {
    return from_candid_record_n47(_uploadFile, _downloadFile, value);
}
function from_candid_TransactionType_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TransactionType): TransactionType {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfilePublic_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfilePublic): UserProfilePublic {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : from_candid_UserProfilePublic_n22(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n33(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GRNEntryPublic]): GRNEntryPublic | null {
    return value.length === 0 ? null : from_candid_GRNEntryPublic_n35(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_IssueEntryPublic]): IssueEntryPublic | null {
    return value.length === 0 ? null : from_candid_IssueEntryPublic_n40(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ItemPublic]): Promise<ItemPublic | null> {
    return value.length === 0 ? null : await from_candid_ItemPublic_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SupplierPublic]): SupplierPublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    username: string;
    lastLoginAt: [] | [_Timestamp];
    createdAt: _Timestamp;
    role: _Role;
    isActive: boolean;
}): {
    id: Principal;
    username: string;
    lastLoginAt?: Timestamp;
    createdAt: Timestamp;
    role: Role;
    isActive: boolean;
} {
    return {
        id: value.id,
        username: value.username,
        lastLoginAt: record_opt_to_undefined(from_candid_opt_n24(_uploadFile, _downloadFile, value.lastLoginAt)),
        createdAt: value.createdAt,
        role: from_candid_Role_n25(_uploadFile, _downloadFile, value.role),
        isActive: value.isActive
    };
}
async function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntityId;
    minimumStock: bigint;
    subcategory: string;
    code: string;
    name: string;
    createdAt: _Timestamp;
    size: string;
    unit: string;
    description: string;
    rackLocation: string;
    isActive: boolean;
    updatedAt: _Timestamp;
    lastPurchaseRate: number;
    category: string;
    gstHsn: string;
    brand: string;
    photo: [] | [_ExternalBlob];
    currentStock: bigint;
    preferredSupplier: string;
}): Promise<{
    id: EntityId;
    minimumStock: bigint;
    subcategory: string;
    code: string;
    name: string;
    createdAt: Timestamp;
    size: string;
    unit: string;
    description: string;
    rackLocation: string;
    isActive: boolean;
    updatedAt: Timestamp;
    lastPurchaseRate: number;
    category: string;
    gstHsn: string;
    brand: string;
    photo?: ExternalBlob;
    currentStock: bigint;
    preferredSupplier: string;
}> {
    return {
        id: value.id,
        minimumStock: value.minimumStock,
        subcategory: value.subcategory,
        code: value.code,
        name: value.name,
        createdAt: value.createdAt,
        size: value.size,
        unit: value.unit,
        description: value.description,
        rackLocation: value.rackLocation,
        isActive: value.isActive,
        updatedAt: value.updatedAt,
        lastPurchaseRate: value.lastPurchaseRate,
        category: value.category,
        gstHsn: value.gstHsn,
        brand: value.brand,
        photo: record_opt_to_undefined(await from_candid_opt_n32(_uploadFile, _downloadFile, value.photo)),
        currentStock: value.currentStock,
        preferredSupplier: value.preferredSupplier
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntityId;
    challanNo: string;
    date: _Timestamp;
    createdAt: _Timestamp;
    createdBy: string;
    invoiceNo: string;
    qcStatus: _QCStatus;
    grnNo: string;
    items: Array<_GRNLineItem>;
    supplierId: _EntityId;
}): {
    id: EntityId;
    challanNo: string;
    date: Timestamp;
    createdAt: Timestamp;
    createdBy: string;
    invoiceNo: string;
    qcStatus: QCStatus;
    grnNo: string;
    items: Array<GRNLineItem>;
    supplierId: EntityId;
} {
    return {
        id: value.id,
        challanNo: value.challanNo,
        date: value.date,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        invoiceNo: value.invoiceNo,
        qcStatus: from_candid_QCStatus_n37(_uploadFile, _downloadFile, value.qcStatus),
        grnNo: value.grnNo,
        items: value.items,
        supplierId: value.supplierId
    };
}
function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntityId;
    status: string;
    issueType: _IssueType;
    issueSlipNo: string;
    date: _Timestamp;
    createdAt: _Timestamp;
    issuedBy: string;
    items: Array<_IssueLineItem>;
    department: string;
    purpose: string;
    machineName: string;
    requestedBy: string;
}): {
    id: EntityId;
    status: string;
    issueType: IssueType;
    issueSlipNo: string;
    date: Timestamp;
    createdAt: Timestamp;
    issuedBy: string;
    items: Array<IssueLineItem>;
    department: string;
    purpose: string;
    machineName: string;
    requestedBy: string;
} {
    return {
        id: value.id,
        status: value.status,
        issueType: from_candid_IssueType_n42(_uploadFile, _downloadFile, value.issueType),
        issueSlipNo: value.issueSlipNo,
        date: value.date,
        createdAt: value.createdAt,
        issuedBy: value.issuedBy,
        items: value.items,
        department: value.department,
        purpose: value.purpose,
        machineName: value.machineName,
        requestedBy: value.requestedBy
    };
}
function from_candid_record_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EntityId;
    qty: bigint;
    itemId: _EntityId;
    transactionType: _TransactionType;
    createdAt: _Timestamp;
    balanceAfter: bigint;
    refId: _EntityId;
}): {
    id: EntityId;
    qty: bigint;
    itemId: EntityId;
    transactionType: TransactionType;
    createdAt: Timestamp;
    balanceAfter: bigint;
    refId: EntityId;
} {
    return {
        id: value.id,
        qty: value.qty,
        itemId: value.itemId,
        transactionType: from_candid_TransactionType_n48(_uploadFile, _downloadFile, value.transactionType),
        createdAt: value.createdAt,
        balanceAfter: value.balanceAfter,
        refId: value.refId
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    manager: null;
} | {
    admin: null;
} | {
    purchaseUser: null;
} | {
    storeUser: null;
}): Role {
    return "manager" in value ? Role.manager : "admin" in value ? Role.admin : "purchaseUser" in value ? Role.purchaseUser : "storeUser" in value ? Role.storeUser : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): QCStatus {
    return "pending" in value ? QCStatus.pending : "approved" in value ? QCStatus.approved : "rejected" in value ? QCStatus.rejected : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    normal: null;
} | {
    emergencyBreakdown: null;
} | {
    directConsumable: null;
}): IssueType {
    return "normal" in value ? IssueType.normal : "emergencyBreakdown" in value ? IssueType.emergencyBreakdown : "directConsumable" in value ? IssueType.directConsumable : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inward: null;
} | {
    issue: null;
}): TransactionType {
    return "inward" in value ? TransactionType.inward : "issue" in value ? TransactionType.issue : value;
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ItemPublic>): Promise<Array<ItemPublic>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ItemPublic_n30(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StockTransaction>): Array<StockTransaction> {
    return value.map((x)=>from_candid_StockTransaction_n46(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GRNEntryPublic>): Array<GRNEntryPublic> {
    return value.map((x)=>from_candid_GRNEntryPublic_n35(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_IssueEntryPublic>): Array<IssueEntryPublic> {
    return value.map((x)=>from_candid_IssueEntryPublic_n40(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfilePublic>): Array<UserProfilePublic> {
    return value.map((x)=>from_candid_UserProfilePublic_n22(_uploadFile, _downloadFile, x));
}
function to_candid_AddGRNRequest_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddGRNRequest): _AddGRNRequest {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_AddIssueRequest_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddIssueRequest): _AddIssueRequest {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
async function to_candid_AddItemRequest_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AddItemRequest): Promise<_AddItemRequest> {
    return await to_candid_record_n17(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_IssueType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IssueType): _IssueType {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_QCStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QCStatus): _QCStatus {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function to_candid_UpdateItemRequest_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateItemRequest): Promise<_UpdateItemRequest> {
    return await to_candid_record_n55(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    issueType: IssueType;
    items: Array<IssueLineItem>;
    department: string;
    purpose: string;
    machineName: string;
    requestedBy: string;
}): {
    issueType: _IssueType;
    items: Array<_IssueLineItem>;
    department: string;
    purpose: string;
    machineName: string;
    requestedBy: string;
} {
    return {
        issueType: to_candid_IssueType_n14(_uploadFile, _downloadFile, value.issueType),
        items: value.items,
        department: value.department,
        purpose: value.purpose,
        machineName: value.machineName,
        requestedBy: value.requestedBy
    };
}
async function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    minimumStock: bigint;
    subcategory: string;
    code: string;
    name: string;
    size: string;
    unit: string;
    description: string;
    rackLocation: string;
    category: string;
    gstHsn: string;
    brand: string;
    photo?: ExternalBlob;
    preferredSupplier: string;
}): Promise<{
    minimumStock: bigint;
    subcategory: string;
    code: string;
    name: string;
    size: string;
    unit: string;
    description: string;
    rackLocation: string;
    category: string;
    gstHsn: string;
    brand: string;
    photo: [] | [_ExternalBlob];
    preferredSupplier: string;
}> {
    return {
        minimumStock: value.minimumStock,
        subcategory: value.subcategory,
        code: value.code,
        name: value.name,
        size: value.size,
        unit: value.unit,
        description: value.description,
        rackLocation: value.rackLocation,
        category: value.category,
        gstHsn: value.gstHsn,
        brand: value.brand,
        photo: value.photo ? candid_some(await to_candid_ExternalBlob_n18(_uploadFile, _downloadFile, value.photo)) : candid_none(),
        preferredSupplier: value.preferredSupplier
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    minimumStock: bigint;
    subcategory: string;
    name: string;
    size: string;
    unit: string;
    description: string;
    rackLocation: string;
    category: string;
    gstHsn: string;
    brand: string;
    photo?: ExternalBlob;
    preferredSupplier: string;
}): Promise<{
    minimumStock: bigint;
    subcategory: string;
    name: string;
    size: string;
    unit: string;
    description: string;
    rackLocation: string;
    category: string;
    gstHsn: string;
    brand: string;
    photo: [] | [_ExternalBlob];
    preferredSupplier: string;
}> {
    return {
        minimumStock: value.minimumStock,
        subcategory: value.subcategory,
        name: value.name,
        size: value.size,
        unit: value.unit,
        description: value.description,
        rackLocation: value.rackLocation,
        category: value.category,
        gstHsn: value.gstHsn,
        brand: value.brand,
        photo: value.photo ? candid_some(await to_candid_ExternalBlob_n18(_uploadFile, _downloadFile, value.photo)) : candid_none(),
        preferredSupplier: value.preferredSupplier
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    challanNo: string;
    date: Timestamp;
    invoiceNo: string;
    qcStatus: QCStatus;
    items: Array<GRNLineItem>;
    supplierId: EntityId;
}): {
    challanNo: string;
    date: _Timestamp;
    invoiceNo: string;
    qcStatus: _QCStatus;
    items: Array<_GRNLineItem>;
    supplierId: _EntityId;
} {
    return {
        challanNo: value.challanNo,
        date: value.date,
        invoiceNo: value.invoiceNo,
        qcStatus: to_candid_QCStatus_n10(_uploadFile, _downloadFile, value.qcStatus),
        items: value.items,
        supplierId: value.supplierId
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: QCStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == QCStatus.pending ? {
        pending: null
    } : value == QCStatus.approved ? {
        approved: null
    } : value == QCStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: IssueType): {
    normal: null;
} | {
    emergencyBreakdown: null;
} | {
    directConsumable: null;
} {
    return value == IssueType.normal ? {
        normal: null
    } : value == IssueType.emergencyBreakdown ? {
        emergencyBreakdown: null
    } : value == IssueType.directConsumable ? {
        directConsumable: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
